language: r

# We have some warnings due to Misztal's binaries
# This avoids issuing an error  
warnings_are_errors: false
sudo: required

r_build_args: --no-build-vignettes

r_check_args: --no-vignettes   # takes too long

r_binary_packages: 
  - Matrix
  - ggplot2
  - lme4
  - nlme
  - reshape2
  - MASS
  - plyr
  - testthat

before_install:
  ## These are needed as pre-requisites for installing INLA
  - Rscript -e "install.packages(c('sp', 'Matrix', 'shiny'), repos = 'http://cran.rstudio.com/')"
  - Rscript -e "install.packages('INLA', repos = 'http:/inla.r-inla-download.org/R/testing')"
